// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameAdmin = "admin"

// Admin mapped from table <admin>
type Admin struct {
	AdminID        int64   `gorm:"column:admin_id;type:int;primaryKey;autoIncrement:true" json:"admin_id"`
	AdminName      *string `gorm:"column:admin_name;type:varchar(255)" json:"admin_name"`
	Password       *string `gorm:"column:password;type:varchar(255)" json:"password"`
	Status         *string `gorm:"column:status;type:varchar(255)" json:"status"`
	Contact        *string `gorm:"column:contact;type:varchar(255)" json:"contact"`
	BlogReviewTime *int64  `gorm:"column:blog_review_time;type:int(10) unsigned zerofill" json:"blog_review_time"`
	ReportTime     *int64  `gorm:"column:report_time;type:int(10) unsigned zerofill" json:"report_time"`
	BanTime        *int64  `gorm:"column:ban_time;type:int(10) unsigned zerofill" json:"ban_time"`
	Address        *string `gorm:"column:address;type:varchar(255)" json:"address"`
}

// TableName Admin's table name
func (*Admin) TableName() string {
	return TableNameAdmin
}
