// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameBlog = "blog"

// Blog mapped from table <blog>
type Blog struct {
	BlogID    int64   `gorm:"column:blog_id;type:int;primaryKey;autoIncrement:true" json:"blog_id"`
	UserID    int64   `gorm:"column:user_id;type:int;not null" json:"user_id"`
	Title     *string `gorm:"column:title;type:varchar(255)" json:"title"`
	Introduce *string `gorm:"column:introduce;type:varchar(255)" json:"introduce"`
	Content   *string `gorm:"column:content;type:varchar(10000)" json:"content"`
	Image     *string `gorm:"column:image;type:varchar(255)" json:"image"`
	File      *string `gorm:"column:file;type:varchar(255)" json:"file"`
	Time      *string `gorm:"column:time;type:varchar(255)" json:"time"`
	Thumbs    *int64  `gorm:"column:thumbs;type:int" json:"thumbs"`
	Favorites *int64  `gorm:"column:favorites;type:int" json:"favorites"`
	Reports   *int64  `gorm:"column:reports;type:int" json:"reports"`
	BlogClass *string `gorm:"column:blog_class;type:varchar(255)" json:"blog_class"`
	Tag       *string `gorm:"column:tag;type:varchar(255)" json:"tag"`
	UserName  *string `gorm:"column:user_name;type:varchar(255)" json:"user_name"`
}

// TableName Blog's table name
func (*Blog) TableName() string {
	return TableNameBlog
}
