// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameComment = "comment"

// Comment mapped from table <comment>
type Comment struct {
	CommentID    int64    `gorm:"column:comment_id;type:int;primaryKey;autoIncrement:true" json:"comment_id"`
	UserID       int64    `gorm:"column:user_id;type:int;not null" json:"user_id"`
	BlogID       int64    `gorm:"column:blog_id;type:int;not null" json:"blog_id"`
	Time         *string  `gorm:"column:time;type:varchar(255)" json:"time"`
	Content      *string  `gorm:"column:content;type:varchar(255)" json:"content"`
	Status       *[]uint8 `gorm:"column:status;type:bit(1)" json:"status"`
	UserName     *string  `gorm:"column:user_name;type:varchar(255)" json:"user_name"`
	ReportReason *string  `gorm:"column:report_reason;type:varchar(255)" json:"report_reason"`
}

// TableName Comment's table name
func (*Comment) TableName() string {
	return TableNameComment
}
