// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameFollow = "follow"

// Follow mapped from table <follow>
type Follow struct {
	UserID   int64 `gorm:"column:user_id;type:int;primaryKey" json:"user_id"`
	FollowID int64 `gorm:"column:follow_id;type:int;primaryKey" json:"follow_id"`
}

// TableName Follow's table name
func (*Follow) TableName() string {
	return TableNameFollow
}
