// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameReport = "report"

// Report mapped from table <report>
type Report struct {
	UserID int64 `gorm:"column:user_id;type:int;primaryKey" json:"user_id"`
	BlogID int64 `gorm:"column:blog_id;type:int;primaryKey" json:"blog_id"`
}

// TableName Report's table name
func (*Report) TableName() string {
	return TableNameReport
}
