// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameThumb = "thumb"

// Thumb mapped from table <thumb>
type Thumb struct {
	UserID int64 `gorm:"column:userId;type:int;primaryKey" json:"userId"`
	BlogID int64 `gorm:"column:blogId;type:int;primaryKey" json:"blogId"`
}

// TableName Thumb's table name
func (*Thumb) TableName() string {
	return TableNameThumb
}
