// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUsermessage = "usermessage"

// Usermessage mapped from table <usermessage>
type Usermessage struct {
	UserMessageID int64   `gorm:"column:user_message_id;type:int;primaryKey;autoIncrement:true" json:"user_message_id"`
	UserID        *int64  `gorm:"column:user_id;type:int" json:"user_id"`
	Content       *string `gorm:"column:content;type:varchar(255)" json:"content"`
	Source        *string `gorm:"column:source;type:varchar(255)" json:"source"`
	Time          *string `gorm:"column:time;type:varchar(255)" json:"time"`
}

// TableName Usermessage's table name
func (*Usermessage) TableName() string {
	return TableNameUsermessage
}
